<?php

use Illuminate\Database\Seeder;

class WatchesSeeder_3 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('watches')->insert(

        	
        [

        	[
        		'img_id'=>'1',
                'vendor_code'=>'ar2447',
                'sex' => 'm',
				'title'=>'Часы Armani Classic Chronograph AR2447',
				'alias'=>'Armani',
				'price'=>'10 150 грн.',    
                'discount'=>'',
                'desc'=>'',
                'status'=>'3',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	],

        	[
        		'img_id'=>'2',
                'vendor_code'=>'ar2501',
                'sex' => 'm',
				'title'=>'Часы Armani Classic Collection AR2501',
				'alias'=>'Armani',
				'price'=>'6 850 грн.',    
                'discount'=>'-10%',
                'desc'=>'',
                'status'=>'3',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	],

        	[
        		'img_id'=>'3',
                'vendor_code'=>'ar0431',
                'sex' => 'm',
				'title'=>'Часы Armani Classic Chronograph AR0431 ',
				'alias'=>'Armani',
				'price'=>'8 150 грн.',    
                'discount'=>'',
                'desc'=>'',
                'status'=>'3',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	],

        	[
        		'img_id'=>'4',
                'vendor_code'=>'ar1737',
                'sex' => 'm',
				'title'=>'Часы Armani Classic Chronograph  AR1737',
				'alias'=>'Armani',
				'price'=>'8 550 грн.',    
                'discount'=>'',
                'desc'=>'',
                'status'=>'3',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	],

        	[
        		'img_id'=>'5',
                'vendor_code'=>'ar1508',
                'sex' => 'm',
				'title'=>'Часы Armani Fossil Ceramic AR1508',
				'alias'=>'Armani',
				'price'=>'11 480 грн.',    
                'discount'=>'',
                'desc'=>'',
                'status'=>'3',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	],

        	[
        		'img_id'=>'6',
                'vendor_code'=>'ar1975',
                'sex' => 'm',
				'title'=>'Часы Armani Classic Chronograph AR1975 ',
				'alias'=>'Armani',
				'price'=>'11 070 грн.',    
                'discount'=>'',
                'desc'=>'',
                'status'=>'3',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	],

        		[
        		'img_id'=>'7',
                'vendor_code'=>'ar1451',
                'sex' => 'm',
				'title'=>'Часы Armani Ceramic Chronograph AR1451',
				'alias'=>'Armani',
				'price'=>'17 870 грн.',    
                'discount'=>'',
                'desc'=>'',
                'status'=>'3',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	],

        		[
        		'img_id'=>'8',
                'vendor_code'=>'ar1400',
                'sex' => 'm',
				'title'=>'Часы Armani Ceramic Chronograph AR1400 ',
				'alias'=>'Armani',
				'price'=>'17 850 грн.',    
                'discount'=>'',
                'desc'=>'',
                'status'=>'3',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	],

        	[
        		'img_id'=>'9',
                'vendor_code'=>'ar5994',
                'sex' => 'm',
				'title'=>'Часы Armani Sports AR5994',
				'alias'=>'Armani',
				'price'=>'5 460 грн.',    
                'discount'=>'',
                'desc'=>'',
                'status'=>'0',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	],

        	[
        		'img_id'=>'10',
                'vendor_code'=>'ar1729',
                'sex' => 'm',
				'title'=>'Часы Armani Classic AR1729',
				'alias'=>'Armani',
				'price'=>'4 900 грн.',    
                'discount'=>'',
                'desc'=>'',
                'status'=>'3',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	],

        	[
        		'img_id'=>'11',
                'vendor_code'=>'ar1792',
                'sex' => 'm',
				'title'=>'Часы Armani Classic Chronograph AR1792 ',
				'alias'=>'Armani',
				'price'=>'12 300 грн.',    
                'discount'=>'',
                'desc'=>'',
                'status'=>'3',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	],

        	[
        		'img_id'=>'12',
                'vendor_code'=>'ar1918',
                'sex' => 'm',
				'title'=>'Часы Armani Classic Collection AR1918',
				'alias'=>'Armani',
				'price'=>'7 900 грн.',    
                'discount'=>'-15%',
                'desc'=>'',
                'status'=>'3',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	],

        	[
        		'img_id'=>'13',
                'vendor_code'=>'ar2473',
                'sex' => 'm',
				'title'=>'Часы Armani Classic Chronograph AR2473',
				'alias'=>'Armani',
				'price'=>'7 900 грн.',    
                'discount'=>'-15%',
                'desc'=>'',
                'status'=>'3',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	],

        	[
        		'img_id'=>'14',
                'vendor_code'=>'ar1410',
                'sex' => 'm',
				'title'=>'Часы Armani Ceramic Chronograph AR1410',
				'alias'=>'Armani',
				'price'=>'7 900 грн.',    
                'discount'=>'-15%',
                'desc'=>'',
                'status'=>'3',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	],

        	[
        		'img_id'=>'15',
                'vendor_code'=>'ar1667',
                'sex' => 'm',
				'title'=>'Часы Armani Classic AR1667',
				'alias'=>'Armani',
				'price'=>'4 729 грн.',    
                'discount'=>'',
                'desc'=>'',
                'status'=>'2',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	],

        	[
        		'img_id'=>'16',
                'vendor_code'=>'ar1485',
                'sex' => 'm',
				'title'=>'Часы Armani Ceramic AR1485',
				'alias'=>'Armani',
				'price'=>'12 586 грн.',    
                'discount'=>'',
                'desc'=>'',
                'status'=>'3',
                'brend_country'=>'Италия', 
                'kind'=>'', 
	            'guarantee'=>'24 месяца', 
	            'series'=>'Classic Chronograph', 
	            'brand_made'=>'Китай', 
	            'clock_size'=>'22 мм ширина ремешка', 
	            'calendar'=>'дата', 
	            'lighting'=>'да', 
	            'body_size'=>'43 мм', 
	            'strap'=>'натуральная кожа, тисненная под крокодила', 
	            'glas'=>'минеральное', 
	            'clock_color'=>'черный', 
	            'body_material'=>'нержавеющая сталь', 
	            'mechanism'=>'японский Miyota', 
	            'style'=>'повседневные', 
	            'mechanism_type'=>'кварцевый', 
	            'clasp'=>'пряжка', 
	            'clasp_color'=>'черный',            
	
        	]


        	]

        	);
    }
}
